import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Footer, Navbar } from "@/components";
import Providers from "./Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
console.log("working");
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-900 via-gray-800 to-black`}
      >
        <div className="min-h-screen">
          <Navbar />
          <Providers>
            <div className="">{children}</div>
          </Providers>
          <Footer />
        </div>
      </body>
    </html>
  );
}
